[directory]
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
"~/Library/Mobile Documents/com~apple~CloudDocs" = "home"
